### PR TITLE
Re: Added chrome extension version for calendarize-webreg

### PR DESCRIPTION
**Pull request by AdoryVo**
See Yen-Ru's [initial PR post](https://github.com/AdoryVo/calendarize-webreg/pull/4) for all earlier details for this PR.
Here is the main motivation for the PR she initially provided:

> As a user of the Arc Browser, the bookmarklet approach sadly doesn't work. Thus, I converted it to a browser extension and thought the extension format might make this project more accessible for some Chronium-alternative-browser users and less tech-savvy students.

I am opening this PR to make further changes towards the effort in this repository via a new branch stemming from her changes.

### CODE REVIEW

**Comment by AdoryVo** [comment]
It may be helpful to look at the commits or use the Files tab to take a look at some of the changes I made.
You can check `dev-notes.md` in the root directory for some notes I'm taking as I'm working.
For one, here are some things I want to finish before finally merging the PR.

- GitHub Workflows
	- Zip the chrome extension and put it into the root directory
	- Upon pushing to `calendarize.js`, minify it and copy it to `chrome-extension`
- Test extension in development (WebReg access / local WebReg page html file needed)
- Publish extension to Chrome Web Store
- Proofread & update README.md
- Extra: Establish basic linting / formatting environment w/ ESLint & Prettier

Yen-Ru, I invited you as a collaborator on the project, you're welcome to make any commits on the new branch towards these goals if you wish. 

**I also currently do not have access to actually test the `calendarize` script as I don't have access to WebReg anymore after graduating & the HTML file of my WebReg schedule that I saved is on a different computer, so it would be very helpful if you could help with testing a bit!**

**Comment by chenyenru** [comment]
Hi Adory,

I've tested the extension on WebReg, and it works ✅ 
To aid in collaboration, I've made the list in the `dev-notes.md` into a checklist.
For future reference, adding a testing GitHub workflow will be most ideal (extra for now though).

Got the collaboration invitation and thank you! As a heads-up, I will work on writing a guide for importing the `ical` events with the correct timezone for students not residing in the PT timezone when they import them.

**Comment by chenyenru** [comment]
Hi Adory,

I've added some edits for README.md as part of the task "Proofread & update README.md."
When you have time, please take a look at it too!

Thanks,
Yen-Ru

**Comment by AdoryVo** [comment]
Looks good! I made some more updates to it as well. I uploaded the extension to the Chrome web store and it is awaiting approval right now - that should make installation a lot easier for users! I also drafted a GitHub release post with the zip file for when we finally merge.

Do you know if the Chrome web store works for Brave and Arc? 
From what I can tell they both support Chrome extensions and Edge seems to also support the web store, so I was hoping they would.

**Comment by AdoryVo** [comment]
alright finished the github workflows, as soon as the extension gets approved on the chrome web store, we should be good to merge

**Comment by AdoryVo** [comment]
Alright, the extension was approved [here](https://chrome.google.com/webstore/detail/calendarize-webreg/jloojoppodnaciefbgkokahoglmgpelf?hl=en&authuser=0) so I will be merging! I pushed one last update to make the web store page look nicer, it should finish pending in the next few days.

**Comment by AdoryVo** [comment]
@chenyenru Thanks again for the help on this! If you wish, you may still contribute with new branches, issues, etc. I'll continue to think about improvements over time as well.

**Comment by chenyenru** [comment]
> Looks good! I made some more updates to it as well. I uploaded the extension to the Chrome web store and it is awaiting approval right now - that should make installation a lot easier for users! I also drafted a GitHub release post with the zip file for when we finally merge.
> 
> Do you know if the Chrome web store works for Brave and Arc? From what I can tell they both support Chrome extensions and Edge seems to also support the web store, so I was hoping they would.

Yep! Both Brave and Arc support Chrome Extensions since they're both developed using Chromium.
Glad to hear the good news! Sorry for the inactivity in the past few days, I've been occupied by adapting to some new changes.

When the Chrome extension request is accepted, please let me know!
And I'll also work on making some improvements too.

**Comment by AdoryVo** [comment]
Sounds good! 👍 
The request has been approved, store page [here](https://chrome.google.com/webstore/detail/calendarize-webreg/jloojoppodnaciefbgkokahoglmgpelf?hl=en&authuser=0)

**Pull request merged**
