### PR TITLE
Added chrome extension for calendarize-webreg

### PR DESCRIPTION
**Pull request by chenyenru**
Hi @AdoryVo,

I'm an incoming UCSD student, and I found your bookmarklet a lifesaver for my class planning.

Thank you for spending the time to do this project, write detailed explanations, and put them up here!

As a user of the Arc Browser, the bookmarklet approach sadly doesn't work. Thus, I converted it to a browser extension and thought the extension format might make this project more accessible for some Chronium-alternative-browser users and less tech-savvy students.

I've added the files and instructions for installations, and I want to make some notes about them:

- The extension's black dot icons are used as placeholders to be replaced with a new logo design.
- Extension's details can be edited in the `calendarize-webreg-chrome-extension/manifest.json`
- It's currently Manifest V2 and won't be supported starting in January 2024. Migration to V3 is needed. [Here's the migration checklist](https://developer.chrome.com/docs/extensions/migrating/checklist/)

Last Notes:
- ⭐️ If this pull request is accepted, please add the zipped extension folder to the release page. Thank you!

### CODE REVIEW

**Comment by AdoryVo** [comment]
Hey Yen-Ru, many thanks for your support and detailed notes! I'd be very on board to support Chromium alternatives like Arc that are getting more and more popular. The next week-ish is quite packed for me but once I get free time after that I will be able to take a close look at merging the PR and addressing everything you mentioned. Thanks again!

**Comment by chenyenru** [comment]
Gotcha, and good luck!

**Comment by AdoryVo** [comment]
Just as an update, I will be getting some more free time in the next few days to start working on this!

**Comment by chenyenru** [comment]
That's great, take your time!

**Comment by AdoryVo** [comment]
Hi Yen-Ru, I worked on some progress towards the extension tonight but I had to do it on a local branch of this repo, so I will be continuing this PR in a new PR for that branch [here](https://github.com/AdoryVo/calendarize-webreg/pull/6).

**Pull request closed without merging**
